export const SELECT_LETTER = 'SELECT_LETTER'
export const REMOVE_LABEL_FROM_ALL_LETTERS = 'REMOVE_LABEL_FROM_ALL_LETTERS'
export const ADD_NEW_LABEL = 'ADD_NEW_LABEL'
export const REMOVE_LABEL = 'REMOVE_LABEL'
export const DELETE_LABEL = 'DELETE_LABEL'
export const SET_LABEL = 'SET_LABEL'
export const MARK_LABEL = 'MARK_LABEL'

